"""add feedback_left_at to orders

Revision ID: 0a2e4adfe3d2
Revises: d500fe688d0d
Create Date: 2026-02-12 21:41:53.366696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a2e4adfe3d2'
down_revision: Union[str, Sequence[str], None] = 'd500fe688d0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('image_paths', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_messages_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_messages_created_at'), ['created_at'], unique=False)

    op.create_table('saved_searches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('max_price', sa.Float(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vouchers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voucher_number', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('voucher_number')
    )
    op.create_table('seen_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('saved_search_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['saved_search_id'], ['saved_searches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voucher_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voucher_id', sa.Integer(), nullable=False),
    sa.Column('account_number', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(), nullable=False),
    sa.Column('debit', sa.Float(), nullable=False),
    sa.Column('credit', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voucher_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('feedback_left_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'vouchers', ['voucher_id'], ['id'])
        batch_op.drop_column('fortnox_voucher_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fortnox_voucher_id', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('feedback_left_at')
        batch_op.drop_column('voucher_id')

    op.drop_table('voucher_rows')
    op.drop_table('seen_items')
    op.drop_table('vouchers')
    op.drop_table('saved_searches')
    with op.batch_alter_table('conversation_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_messages_created_at'))
        batch_op.drop_index(batch_op.f('ix_conversation_messages_chat_id'))

    op.drop_table('conversation_messages')
    # ### end Alembic commands ###
